export const BAGUETEST_LISTE_REQUEST = 'BAGUETEST_LISTE_REQUEST';
export const BAGUETEST_LISTE_SUCCESS = 'BAGUETEST_LISTE_SUCCESS';
export const BAGUETEST_LISTE_FAIL = 'BAGUETEST_LISTE_FAIL';
export const BAGUETEST_DETAILS_REQUEST = 'BAGUETEST_DETAILS_REQUEST';
export const BAGUETEST_DETAILS_SUCCESS = 'BAGUETEST_DETAILS_SUCCESS';
export const BAGUETEST_DETAILS_FAIL = 'BAGUETEST_DETAILS_FAIL';

export const BAGUETEST_CREATE_REQUEST = 'BAGUETEST_CREATE_REQUEST';
export const BAGUETEST_CREATE_SUCCESS = 'BAGUETEST_CREATE_SUCCESS';
export const BAGUETEST_CREATE_FAIL = 'BAGUETEST_CREATE_FAIL';
export const BAGUETEST_CREATE_RESET = 'BAGUETEST_CREATE_RESET';

export const BAGUETEST_UPDATE_REQUEST = 'BAGUETEST_UPDATE_REQUEST';
export const BAGUETEST_UPDATE_SUCCESS = 'BAGUETEST_UPDATE_SUCCESS';
export const BAGUETEST_UPDATE_FAIL = 'BAGUETEST_UPDATE_FAIL';
export const BAGUETEST_UPDATE_RESET = 'BAGUETEST_UPDATE_RESET';

export const BAGUETEST_DELETE_REQUEST = 'BAGUETEST_DELETE_REQUEST';
export const BAGUETEST_DELETE_SUCCESS = 'BAGUETEST_DELETE_SUCCESS';
export const BAGUETEST_DELETE_FAIL = 'BAGUETEST_DELETE_FAIL';
export const BAGUETEST_DELETE_RESET = 'BAGUETEST_DELETE_RESET';

export const BAGUETEST_CATEGORY_LIST_REQUEST = 'BAGUETEST_CATEGORY_LIST_REQUEST';
export const BAGUETEST_CATEGORY_LIST_SUCCESS = 'BAGUETEST_CATEGORY_LIST_SUCCESS';
export const BAGUETEST_CATEGORY_LIST_FAIL = 'BAGUETEST_CATEGORY_LIST_FAIL';

